### ISSUE TITLE
Referer header doesn't seem to work in Chrome

### ISSUE THREAD

**Issue by gurugeek** [piratepx/app#11]
thanks for your cool tracking app! I signed up added <img src="https://app.piratepx.com/ship?p={{PROJECT_ID}}" /> to the head of my website (that runs using NodeJS/Express). Unfortunately all the traffic is recorded as  "/" so I can't see who visits a certain page.  I am not sure where the issue is. My routes are /:pagename without parameters e.g. /readme.

**Comment by jstayton** [comment]
Hey @gurugeek,

Can you point me to your website or share a snippet of your code containing piratepx? It's hard to say where the issue is without more details. Thanks!

**Comment by gurugeek** [comment]
sure https://david.dev has now the piratepix pixel 

strange that all pages appear as "/" in the piratepix stats. 
 
FYI I did a quick clone  of your concept (which is great!) in express and it works fine with
`  page = req.header('Referer');`.

**Comment by jstayton** [comment]
It seems to be working now? I see entries for a few different pages.

**Comment by gurugeek** [comment]
for some pages it does but others not e.g. https://david.dev/arial-vs-helvetica-vs-tahoma is recorded as /
also at the bottom there is 1 visit today in a page that has nothing on it (also not /).  Just thinking what the issue could be :) thanks again for your help

**Comment by jstayton** [comment]
That page doesn't seem to include piratepx. I don't see any requests to it in my developer console, and no reference in the HTML.

> also at the bottom there is 1 visit today in a page that has nothing on it (also not /).

That is a bug that I've now seen a few times. I will open a separate issue for that. Thanks for pointing it out!

**Comment by gurugeek** [comment]
you are welcome, I re added the pixel now (you might want to update the readme to include height="1" width="1" after the image else it can create weird spacing issues). It seems to work now beside the bug of empty pages. Thanks again !

**Comment by gurugeek** [comment]
upon a more attent scrutiny I found out the following:
1) the paths / correctly tracked on piratepix came from my script running in localhost. The live script hits were always recorded as / probably because` req.get('Referrer') ` (I assume this is what you use in the backend) will not work between 2 https servers unless the html code includes` referrerpolicy="no-referrer-when-downgrade" ` this would make it work in Chrome (see [this stackoveflow reply](https://stackoverflow.com/questions/65298715/not-getting-full-path-using-req-getreferrer-if-in-https/65298820#65298820) )

but it will not wotk on Safari unless the user disables this behaviour in the browser itself that by default has "prevent cross-site tracking" enabled.

This is the only reason I could find on why the script is not working in terms of identifying the right pages/paths. 

I would love to hear what you think!  my workaround in a similar script is to pass a parameter with the url together with the site id because I don't think that, given the erratic behaviour,  referrer can be trusted.

**Comment by jstayton** [comment]
Interesting! I didn't realize Chrome had recently changed that. I will definitely update the README with that information.

If you don't want to include that `referrerpolicy`, you can alternatively pass `i` in the query string with the identifier you want to use. Most static site generators / content management systems give you access to the page's path or slug that you can use.

You can also send the full URL in `i`, but keep in mind that the path won't automatically be parsed like with the `Referer` header.

**Comment by gurugeek** [comment]
thank you for the update, I thought that i in the query string was the only way to get some reliable results. Worth nothing that `referrerpolicy="no-referrer-when-downgrade" ` is ignored in safari (hence also ios devices) and there is no way around that unless the users enables it in the settings.  I would say that in this scenario passing an extra parameter is the only way.

**Comment by jstayton** [comment]
I've updated the README with details and included `i` in the default example.

I've also added a `Referrer-Policy` header to piratepx itself.

Thanks again for pointing this out!
