### ISSUE TITLE
isnt my project ID straight up exposed if I use it inside <img> tag

### ISSUE THREAD

**Issue by ST2-EV** [piratepx/app#6]
is that a security issue or is that okay?

**Comment by jstayton** [comment]
Hey Steve,

Your project ID only allows counts to be recorded, and is necessary to differentiate your project from others. Pretty much all analytics apps – really, any app that you integrate into your frontend – require an ID of some sort that's naturally exposed by being embedded in your frontend.

You can't view your dashboard or change settings or anything with just your project ID – for that you need your project secret. You don't want to expose that.

Hope that helps!
