### ISSUE TITLE
Feature Request: add a line that combines all pages

### ISSUE THREAD

**Issue by FelDev** [piratepx/app#7]
First, **thank you** for this. 

If you have time and deem it useful, I'd like to see an extra row in the dashboard which would combine all page views.

Something like:
```
/page1 
        1  2  
/page2
        3  5
total
        4  7
```

---
FWIW, I tried implementing this myself, but kinda got stuck at the environment setup step as I'm not familiar with many of the technologies used.
/web builds nicely and is accessible at localhost:8080, but /api yields
```
TypeError: Cannot read property 'client' of undefined
    at Knex (/Users/[...]/piratepx_app/node_modules/knex/lib/knex.js:22:42)
```
I can trace it up to `/api/db/config.js` where `process.env.DATABASE_URL` is `undefined`, but, idk, seems like this should be trivial and I'm missing something obvious.

**Comment by jstayton** [comment]
Hey Félix,

Yep, totally makes sense. Are you basically wanting to see a single number to compare "activity" on your site from day-to-day?

**Comment by FelDev** [comment]
Yes, exactly!

**Comment by jstayton** [comment]
Got it. I will keep this in mind for the future.

> FWIW, I tried implementing this myself...

It sounds like you just need to copy [`.env.dist`](https://github.com/piratepx/app/blob/development/.env.dist) to `.env`. It should have the correct values for development if you're using the Docker Compose setup.

**Comment by FelDev** [comment]
> It sounds like you just need to copy .env.dist to .env

...indeed.

But then I had an error about `BUGSNAG_API_KEY` not being set. So I created a free account, that solved the problem.

But then I didn't have a `DATABASE_URL` env var set, and now I'm trying to figure out how Postgres works.

Not trying to be bitchy, just letting you know what I stumble onto when trying to contribute. Cheers!

**Comment by FelDev** [comment]
update: got the connection string right and managed to signup on localhost, yay!

**Comment by jstayton** [comment]
Glad you got it figured out! Sorry it was a pain.

I didn't realize the app errors out if there's no `BUGSNAG_API_KEY` set. I definitely don't want to require contributors to setup a Bugsnag account, so I'll work on fixing that. Thanks for letting me know!

**Comment by FelDev** [comment]
You're most welcome!

If you still feel like helping out a n00b, I'm stuck again. Not much further.

After signing up, I can't get past the "Welcome! A few things to start..." page because I don't see a way to increment my page views locally.

I thought querying something like `http://localhost:8080/api/ship?p=<my-localhost-project-id` would do it, but no.

I'm trying the dirtiest hacks but nothing works so I thought I'd just ask how you do it.

**Comment by jstayton** [comment]
The path and port of your `ship` URL are a little off: `http://localhost:3000/ship?p=<my-localhost-project-id>`

For website testing, I just use a bare-bones HTML page with an `<img>` tag:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>piratepx Test</title>
  </head>
  <body>
    <img
      src="http://localhost:3000/ship?p={{PROJECT_ID}}"
    />
  </body>
</html>
```

Otherwise, I just request the `ship` URL on the command line with something like `curl` or [HTTPie](https://httpie.io/).
